import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { fetchECommerceAPI } from "@/redux/e-commerceActions";
import Link from "next/link";
import { addItemToCart } from "@/redux-cart/constants";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const productsData = useSelector(
    (state) => state.eCommerceAPIData.productsList
  );
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(fetchECommerceAPI());
  }, [dispatch]);
  const handleCart = (product) => {
    dispatch(fetchECommerceAPI());
    dispatch(addItemToCart(product));
  };
  return (
    <>
      <Head>
        <title>Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="list-of-product">
          <ul>
            {productsData?.data?.map((product, index) => {
              return (
                <li>
                  <h5 className="title">{product?.title}</h5>
                  <Link
                    className="link"
                    href={"/products/" + product.id}
                    key={product.id}
                  >
                    <img
                      className="product-image"
                      src={product?.image}
                      alt=""
                    />
                  </Link>

                  <p className="category">{product?.category}</p>
                  <p className="price">${product?.price}</p>
                  <p className="rating">
                    {product?.rating?.rate}&nbsp;&nbsp;
                    <span>{product?.rating?.count}</span>
                  </p>
                  <p
                    onClick={(e) => {
                      // e.preventDefault;
                      handleCart(product);
                    }}
                    className={styles.cart}
                  >
                    Add to Cart
                  </p>
                </li>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
}
